### ISSUE TITLE
filter is empty

### ISSUE THREAD

**Issue by upneet2213** [fagbokforlaget/nestjs-mongoose-paginate#27]
Hey! I am fairly new to Nest and server side programming in general so I apologise if the situation I am stuck at is just a small error on my part. I am trying to filter files by the email id of the user they were created by and am hence using encodeURI(`http://localhost:3000/uploads/?filter={"userId":{"$eq":${user.email}}}&page=0&limit=2`) as my url for the get request. However, for some reason my filter is always empty. Would love some help with this. Thanks!

Repo link: https://github.com/upneet2213/file-server-v2

**Comment by feelgood1987** [comment]
Hello,

We have the same issue with the filter, we tried URL-encoding the filter parameter it didn't work.

We're using Nest.js 9

**Comment by feelgood1987** [comment]
We've found the solution in this way, it seems the problem was because of the validation pipe name usage, simply update your controller like this and it'll work:
```typescript
   // first add ValidationPipe import from @nestjs/common
   import { Get, Param, Query, ValidationPipe } from '@nestjs/common';
   
   // change library validation import like this
   import { ValidationPipe as ParseFilterPipe } from '@forlagshuset/nestjs-mongoose-paginate';
   
   // update query validator like this
     async filterAsync(
    @Query( new ValidationPipe({ transform: true,}),
                  new ParseFilterPipe(YourCollectionProperties))
    collectionDto: CollectionDto,
  ): Promise<CollectionResponse ...
```
